hash-format = "sha256"

[[files]]
file = "mods/arsenal.pw.toml"
hash = "3dfb613d8cb47b4f9090d8eff4d67b94a62ca397a6e2bc27aee8fe96d6d264f7"
metafile = true

[[files]]
file = "mods/create-fabric-fixes.pw.toml"
hash = "9f76b957563a81f466be323ae3b8482b0bae291b1f8efaa386cc990c4b87d702"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
hash = "54ed85b42559773c1d59f774b7d1e17938232b97432b20469ead70d69673b6ab"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "b085a13f441287ee000f3d17b49755741ed738a2a296fe349c79c01ed9d81350"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "d68efcc17365557a070fbfe07c1523c041f3c9c41eb637beace220d2c13c849c"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "d4f3d1a419f17ab8672b5d5388a0e1bcf0ced6f386777556e061461db85958c8"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
hash = "db7c47fac84cfc274fcb3ca5d86c2fa974dff11f81c6d7619d69cab59bf6fc99"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "83cf89128bfc6d4a5d1da20565e461f89183127d5960935c1f783ba38b0cb53c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "19eeb8e2d15198628ae414184131017d7b91fa322abef285eccefa573754e3d2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "220290b6585ca56b581de94012e678625aeacc300663113bf848e1872897cb22"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true
