hash-format = "sha256"

[[files]]
file = "config/item_obliterator.json5"
hash = "043c8fc228154d6daa56c884bbecff36c99d06d49d48552fa2829d7b80bd1b2a"

[[files]]
file = "config/kawaiidishes-server.toml"
hash = "25307aaedc6b26d3f8ffc3c27b7b12d8252024fe6ffd7b876ad404574b2cfdbb"

[[files]]
file = "config/natures_spirit-common.toml"
hash = "4cb50915ad71e203f4c89b2a020c386983f0c086a15bd05cc790371cc7ae6da2"

[[files]]
file = "config/subtle_effects/blocks.toml"
hash = "b27504e1d15c1d4e096bd080f44bc420d2002eca50ecc87379e11339ddc76a9c"

[[files]]
file = "config/subtle_effects/entities.toml"
hash = "950875604120c720ecba163a5a95b2a44db94ddbd1eb486f537388cc3ac79e47"

[[files]]
file = "config/subtle_effects/environment.toml"
hash = "31ea2783b395c5d9b7dde5d05ef1fd42e9191843d7bdcf3f6591232d88fb7611"

[[files]]
file = "config/subtle_effects/general.toml"
hash = "ff2c27725362fb1c975aceb4000f42919f8906aacf709f172f4707eb3b73f6c0"

[[files]]
file = "config/subtle_effects/items.toml"
hash = "a9cb0f5f64b9803378a249955c8bd548db1454f589f60db18a1d603c703b2e74"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/apothic-attributes.pw.toml"
hash = "1e1f084a9466d9022785468c8cc0ae295d325fe0edae9550357acb1336f77570"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/asahi.pw.toml"
hash = "08f516419e7401f36096f7081fd01e1dbc80741a95c79ddc90686cb47ea2ae8a"
metafile = true

[[files]]
file = "mods/atlas-api.pw.toml"
hash = "8c6d5170ca4f3e42a3ff45ec2891a24fef98ab136f3e427fc34af23564d9e7dc"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
hash = "03bf4c83390893faab62e2122e9265712a721bd3cd8e0d603f5daddc2549bbd5"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "47ca6d7fe185e6e773347e62863a49ff05c0c7b48e026a97ec6dde3e1fe1e7cc"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "4dac3194a234f244f6b9c754053758d7af758535f50c1a347ff6d0fd05bd94e6"
metafile = true

[[files]]
file = "mods/bbrb.pw.toml"
hash = "d3e067134ecb835b1a02e6f10666033d71ac017a21f17b3a5efeca756482642a"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
hash = "e28be9e32294f80bf7be78a1eca5ad0cdc73e2fa636f9f0561d746b4fd2a1fe5"
metafile = true

[[files]]
file = "mods/biome-dither.pw.toml"
hash = "ea35d17b130a9134b2c39578a1e7e9248fe178ce954f7393cb1844820cc0b107"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "ef7c9b68b65e7baab19dc84903f068de6714e6f306052940f53c747743d3025e"
metafile = true

[[files]]
file = "mods/bundled_.pw.toml"
hash = "0ab032a5ecd0385858fe53ea3b6e40304d0edcf68466ce686665de45eba39abb"
metafile = true

[[files]]
file = "mods/climate-rivers.pw.toml"
hash = "763125b743e375904c81af45f8702b6d6a5b90b5dca1c34f1f77338b75444488"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/colorwheel-patcher.pw.toml"
hash = "44f9462f2bdb7f3254ef7d7639271159b8b2dd0deffb902d5425e883a38b35ca"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "934d5afe2c8d68e991a5e24955c35abde9511a466ab62b34485363ad3f4dc43b"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "52e2cb54ee2933bf00e9b7886f47938a2dce1bf998293be2b38552083ffa5f9a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "aa242da373359065cb62d8e1094e2f17b456f3ea300db145896cf6c6aae43101"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "77115a9f9879a820f30a2b10c11041076a6f60b039bcac59b861416cabc1e0d6"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
hash = "ad35139007c512c76be9945e89ad86e27b3d13bdefb31931486a2a1348321830"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "8e671fbd3a5460a61073cced391ec08efc6b67d765e49015eea45a1f1db159a0"
metafile = true

[[files]]
file = "mods/crag.pw.toml"
hash = "8c652ade823c6226c770a275f94c04b41f0a98a4689ebb226f6edffe29c2648c"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "4c16ee75d3b04443e96d854eec79344293963e9f4beaaf8e7215023e8ef53b88"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "28f531c7efc9e5257235adcb19913ed278f3bc76a36326f28d9fb9303df9e4de"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "7988c367539dd83722d24c50166e60c49c074ab9426afca9aca358b9cd2d0094"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "a8631bdf71f2e2f5423a5203b734e340a0f33c76c117067e4c0e5c5ad6775b41"
metafile = true

[[files]]
file = "mods/end-remastered-additions.pw.toml"
hash = "979f5d8d91d92ea9e5d21f4ccc1643734f30a5b7ed44fa2e02b4ca8eb3778783"
metafile = true

[[files]]
file = "mods/end-villager-outpost.pw.toml"
hash = "cd9d0be82833dacb7377aa42604cdcf254bfc0ef6cb4007e564161a6bdbe851f"
metafile = true

[[files]]
file = "mods/enders-delight.pw.toml"
hash = "32ba80915719801e8974857f088d0322cae29a18bad29caa9061bf4c4930959a"
metafile = true

[[files]]
file = "mods/enderscape.pw.toml"
hash = "edad0d81bfad442929db2ec1433598900883f91714e6b0ed2aa4e59c1d446951"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
hash = "91549cc3de0f099aab19cf786f8ab982585d036f0f56c15e598ac89d3d7276e0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5a13d5f62447f413b36fe1a410f9d0744bf870859cdd5feb165873842066cd25"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "fce3fb2acc36b3d0bbae39fae54819a3c4681afa0027a3886babf3ea94e82af0"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "b349d13a4d8be937cf2cff2b627ec33d6b433b7f5cb96899c483fe710985a26e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "ea72f1530367a4f8c347e197119188d25d876f3fe4ac19c1eb0b4c2ad23ce48c"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "07cb3a168d9801ba54ac07f46d79f98ca9a35405531a07ffa8e26b41a8981f27"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "c88864d93535fddbba7d8a6c9039f4ff6ca0a2aef7b59a7585439d0cef93349e"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "0bba383b6e2daadc345a407a6764dbc387b23dcaf4637e6c32e4b967209b4649"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "aa520002f2dd75e38c6e85bfac57708511b0a9d38286667db04bcfbf4d63ed41"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "fd0673c17a3aaf61f43b63d91b8d18f565ddf91e56822daa8d5d5252510c79b2"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "582b78a087e16d90b2ccca879b99c4cd2df8668fe3ee3b9086e345554b9ae391"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "402ca5410076adcf4bff4211d5d734572e0549955d3613ea0942309ec29a409b"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "b75848642a567ae1057989b991deb832b4ba182cc0ef73f1ed2a736b70b5c09d"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
hash = "a1f1784ed6cb227ec817a3c5dd4c8c1ed26ffc4ab75674fed2e6a6523697acad"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a5dbb701e3c7e377cfbd6a595a0e743eee8471f07962712ac89ae34874f6b65d"
metafile = true

[[files]]
file = "mods/irons-jewelry.pw.toml"
hash = "4518b4f9d39f4e3827ce8828bb27f93e99de69ce77199e0922001f85fad93bb1"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "c7104af995b95c68c28b8425e8a2da698f11500edc4e69056478090982d28915"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
hash = "256fab66e85e9947aa2cad572fb5fb1d94086306ac328dba43be064f495034dc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8675bc2e14673ef0457c5017c866c5d2b2cbea61d241c9324fd66d5a91514f4f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "2fcbfe045a6e2063ed74b00841f82bef29037e383167d5073e354cf227bd06ac"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "62f78f4c3c3fac7e5f0507e2b7a2fdf854a263d34b45c0295df8a07255c37ead"
metafile = true

[[files]]
file = "mods/lets-do-alpine-whispers.pw.toml"
hash = "da7ae6962d7b929b34bb2e05dc9423cdad08366c3d02ad09cd5fb0b82e6ed7a0"
metafile = true

[[files]]
file = "mods/lets-do-bakery-farmcharm-compat.pw.toml"
hash = "363db17d5ec8d103d13e861d0629aac376f3bca5a5daa94b70b4b761b0a49696"
metafile = true

[[files]]
file = "mods/lets-do-candlelight-farmcharm-compat.pw.toml"
hash = "ba5d2bcb0081ffa1042a051e0d4830b0d8f84c0b12c9a51c232206723cbd721f"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "8c4b89a9be0f84a56050c7a24b3d3be219d6d62b710479c5bb8ff3ec12587f8c"
metafile = true

[[files]]
file = "mods/lets-do-herbalbrews.pw.toml"
hash = "aad764bd428196a91a086c4f982f42eb0a628513f9869b2984d4b919ee655b0c"
metafile = true

[[files]]
file = "mods/lets-do-meadow.pw.toml"
hash = "bcf3c950cba1fe6c0ebf4f26f2ab3440b87e1e89dc21ec51776be1cf0e186559"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "3d5d4c97ece8d1470d785fbffb44c1f17ca406931d08dd0cfd5d77745a956979"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b98744192d8b63a91361eb7bdec29a03c2cb95fc700b879826c27b9dc7af28ec"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "4ab60057dd05713d6b8e390b49c8f3d80c3b80f87054ca1a220d475b314d1e50"
metafile = true

[[files]]
file = "mods/morepaths.pw.toml"
hash = "56e1c2a9389565ce734d4ca0a02894088664093cf999f86703d3dd2ffbb9fa77"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "f4bbb9a6169524865e0a82dee3d7a11a5ed2bf133f0d5b730d63a28563a18f7d"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
hash = "5e4854ac1c7932f8526dddf2ff8540f19748fe70f3ed678afd10245cd57b2e4c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "679f984561d6e115c50bcd6d190a699ddefbf9c00e140ebb2816ace9ab681706"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "08f8f358b425d2530ed5bba70eee9e055b1f9f58f7a94ea5435def3968c88466"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "719c46cbc2f422f4be2af849141b71604f5ad02b30317a349537f744860adbf8"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "58fe862ac2e8f705d8d611e4dfc49a85c4391f60981120949d7a2a772b1e96cc"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "5cd30923f8e867bc3a93b84d2c5853c9b6247d8287d276b993ad56629ebb07e1"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/rounded_mod.pw.toml"
hash = "d65acbf65ace3c4b2c06926aa25271e1d621db6f1d5fcfb1068e001146dc478b"
metafile = true

[[files]]
file = "mods/rustic-delight.pw.toml"
hash = "8db743b3b9e97a9351eb7dde818d9d8a0dcbfb2b3b5f4d7b5f3e8374b5d4b8cd"
metafile = true

[[files]]
file = "mods/shields.pw.toml"
hash = "916b446d3021b9257a774ded45f89c7d9a18364d2ea6ca11522709e5468b54cb"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "85e4be7fb8dd729d264ae48c3546882efe2cfe6677ee2720bb8a50069fee2c6d"
metafile = true

[[files]]
file = "mods/shyvvs-trickier-trials.pw.toml"
hash = "551fb561bf5b9dc5a3f197074f17fe80f4a91a5344d0cf894f49bd3bfd102b5d"
metafile = true

[[files]]
file = "mods/skys-flowers.pw.toml"
hash = "6fc45ad1ec2d4e75cb5bf2050a0133820d8e43c60c7161c0057d250c3498450a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c04ad2e883943640d5bc8e519c0b90e6cdd11e5b5a6d095b5838c477021771a0"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "c29a577ea50758240c522295cddecea7b963b0968d6517ca694dbc194296cfcc"
metafile = true

[[files]]
file = "mods/sophisticated-backpackstorage-emerald-upgrade.pw.toml"
hash = "6f21776c5256fe8fef05425b211dedfb65dbec99e32e464039b70771023031b9"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "0c0d7d7785e4ceea16c3ed1c9905bdf33532de1e290b147323c079515f2dc04b"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "d599a1a3cdb3a0ece343aef60f19b52536a11aaaddc1e63c966069d61cee8cf8"
metafile = true

[[files]]
file = "mods/starcaller.pw.toml"
hash = "72520f1cb7f4dcb4f68fc02e37270453b4080a8fee75d043836dc0d488831aef"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "1ee074cf798187e07f45c8f54ddebd53ca4c237773e8a9f394656bf661c10141"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "26fbecd46bfe0a1d9eb02d6a01fad0226dbe1fd6b15e2520cc3ac090d7bfb146"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/trimmed.pw.toml"
hash = "49a89f1fc7f7485ac1b85fefc5f68b48e6678bf88389f57ee04adc6d0cebb687"
metafile = true

[[files]]
file = "mods/wilder-flowers.pw.toml"
hash = "1916525ace41894546cd7b3e952870d818c00baa41f0b440e8977685eeb61174"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "dffcebe24bb99c66172fbe18b9f7d4836f0291df98a8d999bd2f5cc7f73f79f3"
metafile = true
