hash-format = "sha256"

[[files]]
file = "config/item_obliterator.json5"
hash = "043c8fc228154d6daa56c884bbecff36c99d06d49d48552fa2829d7b80bd1b2a"

[[files]]
file = "config/kawaiidishes-server.toml"
hash = "25307aaedc6b26d3f8ffc3c27b7b12d8252024fe6ffd7b876ad404574b2cfdbb"

[[files]]
file = "config/natures_spirit-common.toml"
hash = "4cb50915ad71e203f4c89b2a020c386983f0c086a15bd05cc790371cc7ae6da2"

[[files]]
file = "config/subtle_effects/blocks.toml"
hash = "b27504e1d15c1d4e096bd080f44bc420d2002eca50ecc87379e11339ddc76a9c"

[[files]]
file = "config/subtle_effects/entities.toml"
hash = "950875604120c720ecba163a5a95b2a44db94ddbd1eb486f537388cc3ac79e47"

[[files]]
file = "config/subtle_effects/environment.toml"
hash = "31ea2783b395c5d9b7dde5d05ef1fd42e9191843d7bdcf3f6591232d88fb7611"

[[files]]
file = "config/subtle_effects/general.toml"
hash = "ff2c27725362fb1c975aceb4000f42919f8906aacf709f172f4707eb3b73f6c0"

[[files]]
file = "config/subtle_effects/items.toml"
hash = "a9cb0f5f64b9803378a249955c8bd548db1454f589f60db18a1d603c703b2e74"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/apothic-attributes.pw.toml"
hash = "1e1f084a9466d9022785468c8cc0ae295d325fe0edae9550357acb1336f77570"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/asahi.pw.toml"
hash = "e46d731eb82ec440b4ee81b1c67826faed87b459c711935c31732b5a8176ebd3"
metafile = true

[[files]]
file = "mods/atlas-api.pw.toml"
hash = "8c6d5170ca4f3e42a3ff45ec2891a24fef98ab136f3e427fc34af23564d9e7dc"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
hash = "1e809e2a6b198b3ff3e3c41f5b0d65e8ab3498eece9b0f7e207c39538745a9c6"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "87faa644e1e199e78f12a15ef97b29439dcfeb4eed6a15f09c849af3d24c5e62"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "4dac3194a234f244f6b9c754053758d7af758535f50c1a347ff6d0fd05bd94e6"
metafile = true

[[files]]
file = "mods/bbrb.pw.toml"
hash = "d20f65da219ddd86932b388b5d864516273e2e9f72e60a401944d98a9bf51fa1"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
hash = "d93fb91de2dc3e953fcc0b447a7cc035bb82b3469b6cbbd4e235d8659b9744a0"
metafile = true

[[files]]
file = "mods/biome-dither.pw.toml"
hash = "c77e11d2991d24c6de8a2cc92a604bad11577c05011ac5751e07f1b2214ff53c"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "bc44be60aec1bee981e83233d18cf68af6ebd83d9b7864a5065ff61932a9b3bb"
metafile = true

[[files]]
file = "mods/bundled_.pw.toml"
hash = "692ef1e0ab431738041ca28917381f6cb44e31d1be2d10631f45da969a7905ad"
metafile = true

[[files]]
file = "mods/climate-rivers.pw.toml"
hash = "fa439e7470e236919bd24b82776c17a6d9900c86c590e7fec1436221edff4f3d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "c78021d923ba3e0dd2a4060b4fa4addd343974313cf3278f9e36359e903f442c"
metafile = true

[[files]]
file = "mods/colorwheel-patcher.pw.toml"
hash = "3a580859d853db6dfc01b543514b4760aca07948e67c2f9e620e1c427a8ba8cf"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "43f3d0de5227287b3ea9d37ba9602d90dcba35f87a858f44ab89da2615302e35"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "0b79df1b70eb940f4dd77b0ed1ccb28a00a6ccca10839c71a21d1d3e37b0e71d"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "0383956db6b8abf5a9fbde0465d8ad3fc3b5bf1ec95141dee97d1bf2568352e6"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
hash = "ad35139007c512c76be9945e89ad86e27b3d13bdefb31931486a2a1348321830"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "8e671fbd3a5460a61073cced391ec08efc6b67d765e49015eea45a1f1db159a0"
metafile = true

[[files]]
file = "mods/crag.pw.toml"
hash = "a2e1eff68841614bbf6553c94deaa4bf1d81f8a0e7a82a2687df9c737a46b2ac"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "766a7b228df5aaa70408580f2f30ade16dac67e33dc45183fac42de3301a2492"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "da0c8c2a53f0cca153cab0a4ff146033dc0c6aa782ace99a2edd12824ebde75e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "7988c367539dd83722d24c50166e60c49c074ab9426afca9aca358b9cd2d0094"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "a8631bdf71f2e2f5423a5203b734e340a0f33c76c117067e4c0e5c5ad6775b41"
metafile = true

[[files]]
file = "mods/end-remastered-additions.pw.toml"
hash = "979f5d8d91d92ea9e5d21f4ccc1643734f30a5b7ed44fa2e02b4ca8eb3778783"
metafile = true

[[files]]
file = "mods/end-villager-outpost.pw.toml"
hash = "cd9d0be82833dacb7377aa42604cdcf254bfc0ef6cb4007e564161a6bdbe851f"
metafile = true

[[files]]
file = "mods/enders-delight.pw.toml"
hash = "32ba80915719801e8974857f088d0322cae29a18bad29caa9061bf4c4930959a"
metafile = true

[[files]]
file = "mods/enderscape.pw.toml"
hash = "edad0d81bfad442929db2ec1433598900883f91714e6b0ed2aa4e59c1d446951"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
hash = "91549cc3de0f099aab19cf786f8ab982585d036f0f56c15e598ac89d3d7276e0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5a13d5f62447f413b36fe1a410f9d0744bf870859cdd5feb165873842066cd25"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "fce3fb2acc36b3d0bbae39fae54819a3c4681afa0027a3886babf3ea94e82af0"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "b349d13a4d8be937cf2cff2b627ec33d6b433b7f5cb96899c483fe710985a26e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "ea72f1530367a4f8c347e197119188d25d876f3fe4ac19c1eb0b4c2ad23ce48c"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "07cb3a168d9801ba54ac07f46d79f98ca9a35405531a07ffa8e26b41a8981f27"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "c88864d93535fddbba7d8a6c9039f4ff6ca0a2aef7b59a7585439d0cef93349e"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "0bba383b6e2daadc345a407a6764dbc387b23dcaf4637e6c32e4b967209b4649"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "aa520002f2dd75e38c6e85bfac57708511b0a9d38286667db04bcfbf4d63ed41"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "fd0673c17a3aaf61f43b63d91b8d18f565ddf91e56822daa8d5d5252510c79b2"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "582b78a087e16d90b2ccca879b99c4cd2df8668fe3ee3b9086e345554b9ae391"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "402ca5410076adcf4bff4211d5d734572e0549955d3613ea0942309ec29a409b"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "b75848642a567ae1057989b991deb832b4ba182cc0ef73f1ed2a736b70b5c09d"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
hash = "a1f1784ed6cb227ec817a3c5dd4c8c1ed26ffc4ab75674fed2e6a6523697acad"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a5dbb701e3c7e377cfbd6a595a0e743eee8471f07962712ac89ae34874f6b65d"
metafile = true

[[files]]
file = "mods/irons-jewelry.pw.toml"
hash = "4518b4f9d39f4e3827ce8828bb27f93e99de69ce77199e0922001f85fad93bb1"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "c7104af995b95c68c28b8425e8a2da698f11500edc4e69056478090982d28915"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
hash = "256fab66e85e9947aa2cad572fb5fb1d94086306ac328dba43be064f495034dc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8675bc2e14673ef0457c5017c866c5d2b2cbea61d241c9324fd66d5a91514f4f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "2fcbfe045a6e2063ed74b00841f82bef29037e383167d5073e354cf227bd06ac"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "62f78f4c3c3fac7e5f0507e2b7a2fdf854a263d34b45c0295df8a07255c37ead"
metafile = true

[[files]]
file = "mods/lets-do-alpine-whispers.pw.toml"
hash = "da7ae6962d7b929b34bb2e05dc9423cdad08366c3d02ad09cd5fb0b82e6ed7a0"
metafile = true

[[files]]
file = "mods/lets-do-bakery-farmcharm-compat.pw.toml"
hash = "363db17d5ec8d103d13e861d0629aac376f3bca5a5daa94b70b4b761b0a49696"
metafile = true

[[files]]
file = "mods/lets-do-candlelight-farmcharm-compat.pw.toml"
hash = "ba5d2bcb0081ffa1042a051e0d4830b0d8f84c0b12c9a51c232206723cbd721f"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "8c4b89a9be0f84a56050c7a24b3d3be219d6d62b710479c5bb8ff3ec12587f8c"
metafile = true

[[files]]
file = "mods/lets-do-herbalbrews.pw.toml"
hash = "aad764bd428196a91a086c4f982f42eb0a628513f9869b2984d4b919ee655b0c"
metafile = true

[[files]]
file = "mods/lets-do-meadow.pw.toml"
hash = "bcf3c950cba1fe6c0ebf4f26f2ab3440b87e1e89dc21ec51776be1cf0e186559"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "3d5d4c97ece8d1470d785fbffb44c1f17ca406931d08dd0cfd5d77745a956979"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b98744192d8b63a91361eb7bdec29a03c2cb95fc700b879826c27b9dc7af28ec"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "d9938ca969142eb503d71773b841500b63715787d63d1ac88851a5046c8ceb73"
metafile = true

[[files]]
file = "mods/morepaths.pw.toml"
hash = "56e1c2a9389565ce734d4ca0a02894088664093cf999f86703d3dd2ffbb9fa77"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "f4bbb9a6169524865e0a82dee3d7a11a5ed2bf133f0d5b730d63a28563a18f7d"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
hash = "5e4854ac1c7932f8526dddf2ff8540f19748fe70f3ed678afd10245cd57b2e4c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "679f984561d6e115c50bcd6d190a699ddefbf9c00e140ebb2816ace9ab681706"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "08f8f358b425d2530ed5bba70eee9e055b1f9f58f7a94ea5435def3968c88466"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "719c46cbc2f422f4be2af849141b71604f5ad02b30317a349537f744860adbf8"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "58fe862ac2e8f705d8d611e4dfc49a85c4391f60981120949d7a2a772b1e96cc"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "5cd30923f8e867bc3a93b84d2c5853c9b6247d8287d276b993ad56629ebb07e1"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a4a26382991e10fa067c2bd8bbeb754ced41c2cfaedb54967c192986a2837e23"
metafile = true

[[files]]
file = "mods/rounded_mod.pw.toml"
hash = "d65acbf65ace3c4b2c06926aa25271e1d621db6f1d5fcfb1068e001146dc478b"
metafile = true

[[files]]
file = "mods/rustic-delight.pw.toml"
hash = "8db743b3b9e97a9351eb7dde818d9d8a0dcbfb2b3b5f4d7b5f3e8374b5d4b8cd"
metafile = true

[[files]]
file = "mods/shields.pw.toml"
hash = "916b446d3021b9257a774ded45f89c7d9a18364d2ea6ca11522709e5468b54cb"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "85e4be7fb8dd729d264ae48c3546882efe2cfe6677ee2720bb8a50069fee2c6d"
metafile = true

[[files]]
file = "mods/shyvvs-trickier-trials.pw.toml"
hash = "551fb561bf5b9dc5a3f197074f17fe80f4a91a5344d0cf894f49bd3bfd102b5d"
metafile = true

[[files]]
file = "mods/skys-flowers.pw.toml"
hash = "6fc45ad1ec2d4e75cb5bf2050a0133820d8e43c60c7161c0057d250c3498450a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c04ad2e883943640d5bc8e519c0b90e6cdd11e5b5a6d095b5838c477021771a0"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "c29a577ea50758240c522295cddecea7b963b0968d6517ca694dbc194296cfcc"
metafile = true

[[files]]
file = "mods/sophisticated-backpackstorage-emerald-upgrade.pw.toml"
hash = "6f21776c5256fe8fef05425b211dedfb65dbec99e32e464039b70771023031b9"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "0c0d7d7785e4ceea16c3ed1c9905bdf33532de1e290b147323c079515f2dc04b"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "20c6be321eb8252a0c84944c514ece6a0b2c093f766db89fb98c1554958aa4bf"
metafile = true

[[files]]
file = "mods/starcaller.pw.toml"
hash = "72520f1cb7f4dcb4f68fc02e37270453b4080a8fee75d043836dc0d488831aef"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "1ee074cf798187e07f45c8f54ddebd53ca4c237773e8a9f394656bf661c10141"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "26fbecd46bfe0a1d9eb02d6a01fad0226dbe1fd6b15e2520cc3ac090d7bfb146"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "f114030e6984e30307fc43e37ec812c915aed7f64717d7b364dd84008e045fe4"
metafile = true

[[files]]
file = "mods/trimmed.pw.toml"
hash = "49a89f1fc7f7485ac1b85fefc5f68b48e6678bf88389f57ee04adc6d0cebb687"
metafile = true

[[files]]
file = "mods/wilder-flowers.pw.toml"
hash = "1916525ace41894546cd7b3e952870d818c00baa41f0b440e8977685eeb61174"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "dffcebe24bb99c66172fbe18b9f7d4836f0291df98a8d999bd2f5cc7f73f79f3"
metafile = true
