hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "8088099d7ebac6f66e6a8d6ed060ab6ae83b085b9c8866ee8c2687a9d6a31a82"

[[files]]
file = "config/jade/plugins.json"
hash = "227aeb6203d7c27f72d10fafba2de1995a2f2318a4af60d9d0407f90dbfcbe9e"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/backpack-display.pw.toml"
hash = "a6add04c9ff6ab2477239038cb8497ae1e4c19020955447b965c6367e5800408"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "a2de85ebe9629568398185b5b9554bcc0c54e322b214d78368485a6074a66279"
metafile = true

[[files]]
file = "mods/blanket.pw.toml"
hash = "204a6e607eabf19083f9a4f99e7bc33ff9df95d8c77deaba58f67a6a19f8c811"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "5ba003768a235ab0d811218191166f9aefa4c9a2509341fbba1efd80e18d3676"
metafile = true

[[files]]
file = "mods/carryon-vs-compat.pw.toml"
hash = "b3d72da43e10056cef5c15eabeee3fba4fe72bb48c4559ef172f5880dcf69c46"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15385164e2cd07cce7493a10d6d87df5c7bce587a866613126be3b54b6b28fc7"
metafile = true

[[files]]
file = "mods/collision-fix.pw.toml"
hash = "7f6f281e6a5666d90cc87624242223735a5942797ae77bfa8bebd098322923ce"
metafile = true

[[files]]
file = "mods/colorwheel-patcher.pw.toml"
hash = "0178bf9db8641a3d33a9eb637e14ae2ae454271daa275c8a59269b3546b84636"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "c74b075999921ef7937834c6bb82008cefcb90a6f691208edf708a951c09034c"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e81c635602878f92af9a9c11b92481b25c7aaf3f68cd015dabf5f67201886401"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "964a56ef500d320801315eb45687e51e9352f03615506469979875d2fed41760"
metafile = true

[[files]]
file = "mods/create-storage-refabricated.pw.toml"
hash = "5ce7488cfb370633bb32ff6aaf0865930965d020cd467043f595d243698a3255"
metafile = true

[[files]]
file = "mods/early-loading-screen.pw.toml"
hash = "cb5d0f9fdc6224769a0339389816936f40e0a61b408e5e05d5088f696a799f37"
metafile = true

[[files]]
file = "mods/enchant-the-rainbow.pw.toml"
hash = "361a8e66af214e711d4c2321c927ca8b6dde1ad27d694d6a8281a86c291f5915"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "7a3a066a9e6da4873a54bdad10e6749be5d32026decbc83bd4ebe59f60b9f97f"
metafile = true

[[files]]
file = "mods/eureka.pw.toml"
hash = "ab11fc3cffc3cabd73a8b6647fe64a4f3c95b4e35728812d66d1a1703eac4d02"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "21bdbce23d3cef1dca238e5797f4b87b1e3eb44c8c213e51cd73c51bf55cdced"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "493ed95320ee3cc9c2def86b9d0971c2ca4bb4215921c2a11208bee77d5dbfb5"
metafile = true

[[files]]
file = "mods/idwtialsimmoedm.pw.toml"
hash = "bd23c86b6d4501003043e31eee93e355beed680a514d8439457bb49823743f40"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d9d01681616a8bdb45bbdd0a053b87153bbb77a5ef997325be0b3dc10b7f8979"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "b28167f09bbcaca3fee27d748191ed19ce37b9382bb4ae693a20f415f80ed305"
metafile = true

[[files]]
file = "mods/jade-vs.pw.toml"
hash = "df0c3d7ec59033d2fd944783f73b2bcae09765292d19259781ccb0352d2a4eb4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "435267c3230ba1439f50fa32c3ed3993a4123f870681451aa95acdde5d52622e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "3f678c4ade25a4b4b54aacf25db155658c1ec605bbeaf0ea6b8ed5d0dbc062e1"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "ad302d4bc503de96528b917401fa6f4652cc03bd2e506912d0e5157ecabe9cbd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/packwiz-server-updater.pw.toml"
hash = "90397481159d6f8c13f811b930a4020c7e24c62e35e3cc3596164d312fb0372c"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/rustic-delight.pw.toml"
hash = "c3972869e934ab32ffa3ea44e98784acb278eb5e67648beb93453ca47fa09341"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "83cf89128bfc6d4a5d1da20565e461f89183127d5960935c1f783ba38b0cb53c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "19eeb8e2d15198628ae414184131017d7b91fa322abef285eccefa573754e3d2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "0238d3e484f1829aaabb3b2482e528e192f3124fad89d81f43d7b60406e17d71"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "6e5a8f947f77a0a9cf18347edd01a08fc725c2ecaa10cf61e6b429a54e50a463"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "f010bbe486733738e92241d10f403e28a8feeb40b45ec3af3b2270523f955216"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
hash = "fc06b9fc1fc94b5cb163b4240ca64065653534bf36125b71a2c125363b29284c"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "220290b6585ca56b581de94012e678625aeacc300663113bf848e1872897cb22"
metafile = true

[[files]]
file = "mods/wakes.pw.toml"
hash = "e260f1729799f726c6508c7e61a8ce7784304e58d55495cbc8823d0103fcfee5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true
