name = "The Tiv Pack"
author = "tiv"
version = "0.0.5c-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06fc0d49c74fa557e2d601d67651078d0322dd5c14bf562934f08cc7e60261b5"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
