name = "The Tiv Pack"
author = "tiv"
version = "0.0.6-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b070580b1abf2260908a2a1a5a2471309b6fe5aa8fca06017ceff1d03463365"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
