name = "The Tiv Pack"
author = "tiv"
version = "0.0.14a@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4713f047fe3cc7dbbfac7ef6d3490e907817a24a41432237e79db5a9124aa35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
