name = "The Tiv Pack"
author = "tiv"
version = "0.0.14c@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fff9ff940c0b011fa10dccffe80fba9fb390e9831deb17ad686032c9ac4e63f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
