name = "The Tiv Pack"
author = "tiv"
version = "0.1.8g-pre@0.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e55e7d384b60c8e535efa0d7e67487733d8fb27b8f94414b1941db6125d69324"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
