name = "The Tiv Pack"
author = "tiv"
version = "0.0.6a-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ea7e3a340b28799d4fdb4fcb5a28a3bcf87360e42698bf67006e7e652de625d"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
