name = "The Tiv Pack"
author = "tiv"
version = "0.0.3a-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8328fb7e73fdfa0cfa6ed6c87822bff96f7d1e96f87b9f14ff40a1f2ca49c558"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
