name = "The Tiv Pack"
author = "tiv"
version = "0.0.5b-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "709efdfd4aecce8a3b420f34cd382f83c2a01b306347bc935aa64e36ef22a0b4"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
