name = "The Tiv Pack"
author = "tiv"
version = "0.0.14e@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef7259c9ffa979c9a463d9fa6c30e839217435de7998f17c6f43b701c1b44e30"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
