name = "The Tiv Pack"
author = "tiv"
version = "0.0.8b-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bbaca89b1da9dd0d57a4b3386117a7bb0a2c7cbe9b37c43a0fe1f3cf87e65fd"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
