name = "The Tiv Pack"
author = "tiv"
version = "0.0.10@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c74477604f31816f6380facc2ab581dfcfbb9e49d4be7a96768a62241eb6b1bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
