name = "The Tiv Pack"
author = "tiv"
version = "0.1.0-pre@0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97e5b2990a2e66a26ddd95c6577cfc2353bff949e762e4e2254bfd547fa79ff3"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
