name = "The Tiv Pack"
author = "tiv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be84c8393e841ee1dfd9572d7b89e50266c4ac0c3e719da00ca99ca449e2e5d2"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
