name = "The Tiv Pack"
author = "tiv"
version = "0.0.9@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "066bc84f37e108ec430f9dfacaa6906c876046c3800c9e18536e3fded31bbdae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
