name = "The Tiv Pack"
author = "tiv"
version = "0.0.12@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a55c255bab713456b9580242958054c650ce40973a0b1333d289101dbda4676d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
