name = "The Tiv Pack"
author = "tiv"
version = "0.0.10a@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc35a60344347c533335a308e15ac85d320bcc910b74237ead5645d68309e651"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
