name = "The Tiv Pack"
author = "tiv"
version = "0.0.10@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fef0deceaaea62764b7c8aaa08176ebbe12e1060f7baa877434dec6fde132f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
