name = "The Tiv Pack"
author = "tiv"
version = "0.0.11@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0d05448c83bea842d237b47fa8a313a6fb188ecb05503aa0d04404852712fd4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
