name = "The Tiv Pack"
author = "tiv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1893a13d4ba6eb5d8c6068ca50b82de93640ed6c46c8117408403d3da5ab1c57"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
