name = "The Tiv Pack"
author = "tiv"
version = "1.0.3@rel"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c76560ec595951a9d8104b472603931b95439b10b166618d6cce762ffbf6295"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
