name = "The Tiv Pack"
author = "tiv"
version = "0.0.4-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22e85d9abb5ce85c93699b5e87df83d20c4aaf0801c3bf24d782d74208ebf564"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
