name = "The Tiv Pack"
author = "tiv"
version = "0.0.8@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fa891966f8cd84e9ed093052e095bbe4c3f3c5bdd9efe112fdcdd1c0af44954"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
