name = "The Tiv Pack"
author = "tiv"
version = "1.0.1@rel"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddacf409ff05c837d429c34294afbe203056b6f60bd4d9b864f94146f860bc02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
