name = "The Tiv Pack"
author = "tiv"
version = "0.0.6@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ad56dd91afe4f18d60c2a2f781165b916cc8c9f361cc808346d634d11671d08"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
