name = "The Tiv Pack"
author = "tiv"
version = "1.0.2@rel"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6bd94eb4b7a7450ed6862a2ec544a902b105df075d8175adaebf35178147bae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
