name = "The Tiv Pack"
author = "tiv"
version = "0.1.9d-pre@0.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b329e87799dc2cca20292b21d33c0e925d614a90feefe7206d0432a98af9def5"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
