name = "The Tiv Pack"
author = "tiv"
version = "0.0.14b@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a4cd0fff815bf9822a2b403b6338f364452c3002013a8468dabe887495cd0b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
