name = "The Tiv Pack"
author = "tiv"
version = "0.0.1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88b04d015ff653b57cc53e319288daa9ecff95f8b3edf0e3586b0db88f1ea900"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
