name = "The Tiv Pack"
author = "tiv"
version = "0.0.14e@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9e1fa62d01756a69c6e9c1dfda63d1cece09cd2e247708599dad337f33400db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
