name = "The Tiv Pack"
author = "tiv"
version = "0.0.9@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40b89c24dfb85addafd50ebfb3f9579a9fb8ec77a718d75219d9f30136378dc4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
