name = "The Tiv Pack"
author = "tiv"
version = "0.0.5a@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "138ed66699fdec1b57ca9303fb567bcd0717f62e18ca85d2670be252e0e10975"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
