name = "The Tiv Pack"
author = "tiv"
version = "1.0.3@rel"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20c4300afad69d621700da22f58f1fc401b905d18924c70a79ecee8b3b57001b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["Fabric"]
