name = "The Tiv Pack"
author = "tiv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72b229843ad8f3f8d2014e2cddf1a7a239bc19a752dc608f89bc4c096e70395b"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
