name = "The Tiv Pack"
author = "tiv"
version = "0.0.14a@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68958d440f37d4ebc7eedb50dda45c800a47224ed3afd4b703d0fbea1081afda"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
