name = "The Tiv Pack"
author = "tiv"
version = "1.0.3@rel"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00bd018a20c3c4dd3c28be4ef35a645924886378592f7955027c3966ed007b76"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["Fabric"]
