name = "The Tiv Pack"
author = "tiv"
version = "0.1.4-pre@0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba58a8a20bac8e870a653e13f8b65b8b02f89c54cdf54317eb0621133b678eac"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
