name = "The Tiv Pack"
author = "tiv"
version = "0.0.8@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8c215f291bec3f67163b25bfe295689b097dd209f238bdda1d5e4c986c8a263"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
