name = "The Tiv Pack"
author = "tiv"
version = "0.0.10@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85070f55727e716c6362bcf944e8644c28e315c0f4282360777bf8e6d1d0761d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
