name = "The Tiv Pack"
author = "tiv"
version = "0.0.7b-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42cdf62e30d4751586e39dc7fb037cca3dde0947bc5a3d13af5a3313b7987ed7"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
