name = "The Tiv Pack"
author = "tiv"
version = "0.0.14@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8464140b0ef8b85f44c7dcb8532003104cb061cce78dcf35b3b04ca17e988f93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
