name = "The Tiv Pack"
author = "tiv"
version = "0.0.12@dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b33409a2150150c19cc657ede0a293c68c8205d816745660100169a545b1c4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
