name = "The Tiv Pack"
author = "tiv"
version = "0.1.8f-pre@0.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c859b83b5600e72dab5fc3bd41d39b12fecf5e330cab57cbc4c1c2190cf1313"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
