name = "The Tiv Pack"
author = "tiv"
version = "0.0.7a-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "836b2e42f13470b3b26ec164354da0ab4c39d45d2f98148d9894e3320cad1b0d"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
