name = "The Tiv Pack"
author = "tiv"
version = "1.0.0@rel"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c0d313e73f9dad771c31d8df52c82272e16b52fa3012566b1ea3c60001d6a77"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["Fabric"]
